version: '3.8'
services:
  event-database:
    image: mysql:9.3.0
    container_name: event-database
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: