// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using course_service.Data;

#nullable disable

namespace course_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250623025515_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("course_service.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_description");

                    b.Property<string>("CategoryImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category_image_url");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("course_service.Data.Entities.CourseEntity", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("course_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_description");

                    b.Property<string>("CourseImageUrl")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("course_image_url");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("course_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("course_service.Data.Entities.EnrollmentEntity", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("completion_date");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("progress");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("course_service.Data.Entities.LessonEntity", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("lesson_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("LessonDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lesson_description");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lesson_name");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("module_id");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10, 5)")
                        .HasColumnName("order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("LessonId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("course_service.Data.Entities.LessonPartEntity", b =>
                {
                    b.Property<Guid>("LessonPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("lesson_part_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lesson_id");

                    b.Property<string>("LessonPartContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lesson_part_content");

                    b.Property<string>("LessonPartName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lesson_part_name");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10, 5)")
                        .HasColumnName("order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("LessonPartId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonContents");
                });

            modelBuilder.Entity("course_service.Data.Entities.ModuleEntity", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("module_id");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ModuleDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module_description");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("module_name");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(10, 5)")
                        .HasColumnName("order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("ModuleId");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("course_service.Data.Entities.CourseEntity", b =>
                {
                    b.HasOne("course_service.Data.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("course_service.Data.Entities.EnrollmentEntity", b =>
                {
                    b.HasOne("course_service.Data.Entities.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("course_service.Data.Entities.LessonEntity", b =>
                {
                    b.HasOne("course_service.Data.Entities.ModuleEntity", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("course_service.Data.Entities.LessonPartEntity", b =>
                {
                    b.HasOne("course_service.Data.Entities.LessonEntity", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("course_service.Data.Entities.ModuleEntity", b =>
                {
                    b.HasOne("course_service.Data.Entities.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");
                });
#pragma warning restore 612, 618
        }
    }
}
